package com.bth.anomalydetection.beans;

public enum AnomalyType {
    NONE,
    VESSEL_NOT_INFORMED_PORT,
    ARRIVAL_TIME_MISMATCHED,
    VESSEL_ENTERED_PORT_WITHOUT_NOTICE,
    VESSEL_NOT_USED_PILOT,
    UNUSUAL_TRIP_PATTERN,
    VESSEL_NOT_LEFT_PORT,
    VESSEL_NOT_ENTERED_PORT,
    VESSEL_ORDERED_PILOT_AND_NOT_INFORMED_PORT,
    VESSEL_MOORED_PORT,
    SUSPECTED_OF_SMUGGLING,
    UNUSUAL_TRIP_PATTERN_AND_VESSEL_NOT_INFORMED_PORT, //A1,A5
    UNUSUAL_TRIP_PATTERN_AND_VESSEL_ARRIVAL_TIME_MISMATCHED,//A2,A5
    UNUSUAL_TRIP_PATTERN_AND_VESSEL_NOT_ENTERED_PORT, //A7,A5
    UNUSUAL_TRIP_PATTERN_AND_VESSEL_ORDERED_PILOT_AND_NOT_INFORMED_PORT,//A8,A5
    VESSEL_ENTERED_PORT_WITHOUT_NOTICE_AND_NOT_LEFT_PORT_ON_TIME, //A3,A6			
    VESSEL_ARRIVAL_TIME_MISMATCHED_AND_VESSEL_NOT_USED_PILOT,//A2,A4				
    UNUSUAL_TRIP_PATTERN_AND_VESSEL_NOT_USED_PILOT,// A4,A5	
    VESSEL_NOT_ENTERED_PORT_AND_NOT_USED_PILOT,//A7,A4		
    VESSEL_ORDERED_PILOT_AND_NOT_INFORMED_PORT_AND_VESSEL_NOT_USED_PILOT,//A8,A4
    UNUSUAL_TRIP_PATTERN_AND_VESSEL_NOT_USED_PILOT_AND_VESSEL_ARRIVAL_TIME_MISMATCHED,//A2,A4,A5
    UNUSUAL_TRIP_PATTERN_AND_VESSEL_NOT_ENTERED_PORT_AND_VESSEL_NOT_USED_PILOT,//A7,A4,A5
    UNUSUAL_TRIP_PATTERN_AND_VESSEL_ORDERED_PILOT_AND_NOT_INFORMED_PORT_AND_VESSEL_NOT_USED_PILOT//A8,A4,A5
}